# permissions for end users to view serviceoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: service-operator
    app.kubernetes.io/part-of: service-operator
    app.kubernetes.io/managed-by: kustomize
  name: serviceoperator-viewer-role
rules:
- apiGroups:
  - operator.wnguddn777.com
  resources:
  - serviceoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.wnguddn777.com
  resources:
  - serviceoperators/status
  verbs:
  - get
